settings:
  batch_size : 32
  num_workers : 0
  num_epochs : 20
  lr_rate : 5e-4
  hidden_dim : 128
  num_layers : 12
  alpha : 0.5
  sequence_length : 10

directories:
  para_dir : 'dataset/optimized'
  checkpoint : "src/models/PINN0310_01.pth" # freshly trained model name
  ref : 'dataset/reference'
  cool : 'dataset/cooling'