project: "heat exchanger"
name: "test_run"
version: v0

train_settings:
  batch_size : 4096
  num_epochs : 30
  num_workers : 16
  pin_memory : False
  seed : 37
  
preprocess:
  scaler : normalize
  descaler : zunnormalize
  sequence_length : 30
  time_step : 2
  test_size : 0.2
  random_state : 37

model:
  dataloader : Parameterloader
  model_class : lstmPINN
  lstm_size : 256
  lstm_layers : 3
  output_size : 6
  drop_rate : 0.2
  w_res : 1
  w_theta : 40
  w_ode : 1

loss : ODE

optimizer:
  optim_class: Adam
  scheduler_class: CosineAnnealingLR
  lr: 1e-4
  eta_min : 1e-5
  weight_decay: 1e-5
  patience : 15

directories:
  checkpoint : "src/weights"
  data_root : "dataset/dataset.csv"
  test_root : "dataset/test.csv"
  inf_root : "src/inference"


optimization : 
  
  num_workers : 16
  pin_memory : False
  batch_size : 4096
  num_epochs : 30
  seed : 37
  test_size : 0.2
  random_state : 37