project: "hybrid_model"
name: "initial_test_run"
version: v0

optimize_settings:
  num_workers : 16  
  pin_memory : False
  seed : 37
  num : 1000
  noise : 5

optimizer:
  optim_class: Adam
  scheduler_class: CosineAnnealingLR
  lr: 1e-4
  max_iter : 500
  tolerance : 1
  temperature : -10 # desired temperature of T_cool
  step : 10 # step until desired temperature of T_ref_in changes
  
preprocess:
  scaler : normalize
  descaler : unnormalize
  sequence_length : 30 
  random_state : 37

directories: 
  checkpoint : "src/weights/best_run_selection_0512_vF.pth"
  data_root : "../../MATLAB/SIMULINK/optimization"

cost: Quad