
# check if optimizing or PINN training

project: "heat exchanger"
name: "best_run_selection_30"
version: v1

train_settings:
  batch_size : 4096
  num_epochs : 1000
  num_workers : 16
  pin_memory : False
  seed : 37
  
preprocess:
  scaler : normalize
  descaler : unnormalize
  sequence_length : 30
  time_step : 2
  test_size : 0.2
  random_state : 37
  horizon : 5

model:
  dataloader : Parameterloader
  model_class : lstmPINN
  lstm_size : 512
  lstm_layers : 5
  output_size : 6
  drop_rate : 0.0
  w_res : 5
  w_theta : 30
  w_ode : 1

loss : ODE

optimizer:
  optim_class: Adam
  scheduler_class: CosineAnnealingLR
  lr: 1e-4
  eta_min : 1e-9
  weight_decay: 0
  patience : 20

directories:
  checkpoint : "src/weights/"
  data_root : "dataset/dataset.csv"
  test_root : "dataset/test.csv"
  inf_root : "src/inference"

optimization : 
  project: "eMPC optimization"
  name: "test_run"
  version: v0

  optimize_settings:
    num_workers : 16  
    pin_memory : False
    seed : 37
    num : 500

  optimizer:
    optim_class: Adam
    scheduler_class: ReduceLROnPlateau
    lr: 1e-4
    eta_min : 1e-8
    max_iter : 1000
    tolerance : 1
    temperature : -12 # desired temperature of T_cool
    step : 40 # step until desired temperature of T_ref_in changes

  model:
    model_class : lstmPINN
    dataloader : Realtimeloader
    lstm_size : 512
    lstm_layers : 4
    output_size : 6
    
  preprocess:
    scaler : normalize
    descaler : unnormalize
    seq_len : 10
    time_step : 2
  
  directories: 
    checkpoint : "src/weights/total_test_run_0520_v3.pth"
    data_root : "../../MATLAB/SIMULINK/optimization"

  cost: eMPC